# Generated by Django 4.1.5 on 2023-10-10 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('values', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mission_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('vision_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('values_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('our_skills', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
