# Generated by Django 4.1.5 on 2023-10-10 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_articles_delete_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='mission_pic',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='values_pic',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='vision_pic',
        ),
        migrations.AddField(
            model_name='articles',
            name='index_about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
