# Generated by Django 4.1.5 on 2023-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_quetstions'),
    ]

    operations = [
        migrations.CreateModel(
            name='İmage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='quetstions',
            name='answer',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='quetstions',
            name='question',
            field=models.TextField(max_length=250),
        ),
    ]
