# Generated by Django 4.1.5 on 2023-10-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_i̇mage_alter_quetstions_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='İmage',
            new_name='Image',
        ),
    ]
