# Generated by Django 4.1.5 on 2023-10-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_rename_i̇mage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pic/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='kisiler',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resimler/'),
        ),
    ]
